### ISSUE TITLE
After updating cell, calculation isn't run

### ISSUE THREAD

**Issue by urbaitel** [KeeTraxx/kexcel#6]
OK, so far I got your module working on an existing file, editing a cell.    How can I trigger (hopefully possible) the calculations on other cells on edit?

**Comment by KeeTraxx** [comment]
Thanks for trying out!

I'm afraid the calculations aren't run, since kexcel is only modifying the underlying OOXML format and doesn't have a calculation engine of its own.

Calculations are done when you open it in a spreadsheet editor again.

Or you might do the calculations in your code and put them into the spreadsheet as values.

Sorry for having to disappoint you :(
